### ISSUE TITLE
Collection type flowchart image is broken

### ISSUE THREAD

**Issue by szaboopeeter** [agoda-com/standards-c-sharp#2]
The collection type flowchart image does not render.

Page: https://github.com/agoda-com/standards-c-sharp/blob/master/docs/collections/choosing-collection-implementation.md

Source: https://github.com/agoda-com/standards-c-sharp/blame/master/docs/collections/choosing-collection-implementation.md#L19

Also not sure if google drive is the best place to refer it from.

**Comment by mikechamberlain** [comment]
Thanks! fixed now.
